<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cars_Bikes</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.68.0.3428" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controllers\TwoWheeler\UpcomingBike\" />
    <Folder Include="Views\UpcomingBike\" />
    <Folder Include="wwwroot\.well-known\pki-validation\" />
    <Folder Include="Services\" />
    <Folder Include="Views\Wishlist\" />
    <Folder Include="Views\Review\" />
    <Folder Include="Views\LatestNews\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Services\" />
    <None Remove="Views\Wishlist\" />
    <None Remove="Views\Review\" />
    <None Remove="Controllers\Api\" />
    <None Remove="Views\LatestNews\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\TwoWheeler\LatestNews\2024\Nov\Nov292024NewsDetails1.cshtml" />
    <None Include="Views\TwoWheeler\LatestNews\2024\Nov\Nov52024NewsDetails1.cshtml" />
  </ItemGroup>
</Project>