// <auto-generated />
using System;
using Cars_Bikes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cars_Bikes.Migrations
{
    [DbContext(typeof(TwoWheelerDB))]
    [Migration("20240812130807_RemovelenghtfromTWLatestNews")]
    partial class RemovelenghtfromTWLatestNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cars_Bikes.Models.NewsLetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsLetters");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWCharging", b =>
                {
                    b.Property<int>("TWChargingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWChargingId"));

                    b.Property<string>("ChargingAtChargingStation")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ChargingAtHome")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWChargingId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWChargings");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWDimensionsAndCapacity", b =>
                {
                    b.Property<int>("TWDimensionsAndCapacityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWDimensionsAndCapacityId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FuelCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelReserve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GroundClearance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("KerbWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SaddleHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Wheelbase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TWDimensionsAndCapacityId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWDimensionsAndCapacities");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWElectricals", b =>
                {
                    b.Property<int>("TWElectricalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWElectricalsId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DRLs")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DistanceToEmptyIndicator")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Headlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEDTailLights")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LowFuelIndicato")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PilotLamps")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TailLight")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TurnSignalLamp")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWElectricalsId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWElectricals");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWEngineAndTransmission", b =>
                {
                    b.Property<int>("TWEngineAndTransmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWEngineAndTransmissionId"));

                    b.Property<string>("Clutch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompressionRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolingSystem")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Displacement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmissionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelSupply")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("GearBox")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Ignition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxTorque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumOfCylinders")
                        .HasColumnType("int");

                    b.Property<string>("Starting")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ValvePerCylinder")
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWEngineAndTransmissionId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWEngineAndTransmissions");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWFeatures", b =>
                {
                    b.Property<int>("TWFeaturesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWFeaturesId"));

                    b.Property<string>("ABS")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AdditionalFeaturesOfVariant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdjustableWindshield")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyGraphics")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Clock")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistanceToEmptyIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelGauge")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("InstrumentConsole")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LEDTailLight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odometer")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PassengerFootrest")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SeatType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Speedometer")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Tachometer")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tripmeter")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWFeaturesId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWFeatures");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWImageColorPrice", b =>
                {
                    b.Property<int>("TWImageColorPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWImageColorPriceId"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWImageColorPriceId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWImageColorPrices");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWLatestNews", b =>
                {
                    b.Property<int>("TWLatestNewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWLatestNewsId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewsHeading")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewsSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TwoWBrandId")
                        .HasColumnType("int");

                    b.HasKey("TWLatestNewsId");

                    b.HasIndex("TwoWBrandId");

                    b.ToTable("TWLatestNews");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWMileageAndPerformance", b =>
                {
                    b.Property<int>("TWMileageAndPerformanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWMileageAndPerformanceId"));

                    b.Property<decimal?>("CityMileage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HighwayMileage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OverallMileage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWMileageAndPerformanceId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWMileageAndPerformances");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWMotorAndBattery", b =>
                {
                    b.Property<int>("TWMotorAndBatteryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWMotorAndBatteryId"));

                    b.Property<string>("BatteryCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriveType")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PeakPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWMotorAndBatteryId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWMotorAndBatteries");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWOrFWContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TWOrFWContactUs");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWSafety", b =>
                {
                    b.Property<int>("TWSafetyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWSafetyId"));

                    b.Property<string>("AdditionalFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineKillSwitch")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PassSwitch")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RidingModes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TractionControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWSafetyId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWSafety");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWSpec", b =>
                {
                    b.Property<int>("TWSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWSpecId"));

                    b.Property<string>("BodyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontBrake")
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("FuelCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Milage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RearBrake")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWSpecId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWSpec");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWTyresAndBrakes", b =>
                {
                    b.Property<int>("TWTyresAndBrakesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWTyresAndBrakesId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FrontBrakeDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FrontSuspension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadialTyre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RearBrakeDiameter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RearSuspension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWTyresAndBrakesId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWTyresAndBrakes");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWUnderpinning", b =>
                {
                    b.Property<int>("TWUnderpinningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWUnderpinningId"));

                    b.Property<string>("BrakesFront")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BrakesRear")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SuspensionFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspensionRear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TWVarientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TubelessTyre")
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TyreSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WheelSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WheelType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWUnderpinningId");

                    b.HasIndex("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWUnderpinnings");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWVarient", b =>
                {
                    b.Property<int>("TWVarientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWVarientId"));

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TWName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TwoWheelerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Varients")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TWVarientId");

                    b.HasIndex("TwoWheelerId");

                    b.ToTable("TWVarients");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TwoWheeler", b =>
                {
                    b.Property<int>("TwoWheelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TwoWheelerId"));

                    b.Property<int?>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEV")
                        .HasColumnType("bit");

                    b.Property<string>("LaunchDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesOrComments")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TWImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopPrice")
                        .HasColumnType("int");

                    b.Property<int?>("TwoWBrandId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TwoWheelerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(30)");

                    b.HasKey("TwoWheelerId");

                    b.HasIndex("TwoWBrandId");

                    b.ToTable("TwoWheelers");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TwoWheelerBrand", b =>
                {
                    b.Property<int>("TWBrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TWBrandId"));

                    b.Property<string>("BrandLogoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsEV")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPetrol")
                        .HasColumnType("bit");

                    b.HasKey("TWBrandId");

                    b.ToTable("TWBrands");
                });

            modelBuilder.Entity("Cars_Bikes.Models.UpcomingBike", b =>
                {
                    b.Property<int>("UpcomingBikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpcomingBikeId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedLaunchDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FilterLaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TwoWBrandId")
                        .HasColumnType("int");

                    b.Property<string>("UpcomingBikeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpcomingBikeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpcomingBikeId");

                    b.HasIndex("TwoWBrandId");

                    b.ToTable("TWUpcomingBikes");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWCharging", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWDimensionsAndCapacity", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWElectricals", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWEngineAndTransmission", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWFeatures", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWImageColorPrice", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWLatestNews", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TwoWheelerBrand", "TwoWheelerBrands")
                        .WithMany()
                        .HasForeignKey("TwoWBrandId");

                    b.Navigation("TwoWheelerBrands");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWMileageAndPerformance", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWMotorAndBattery", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWSafety", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWSpec", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWTyresAndBrakes", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWUnderpinning", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TWVarient", "TWVarients")
                        .WithMany()
                        .HasForeignKey("TWVarientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany()
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TWVarients");

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TWVarient", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TwoWheeler", "TwoWheeler")
                        .WithMany("TWVarients")
                        .HasForeignKey("TwoWheelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwoWheeler");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TwoWheeler", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TwoWheelerBrand", "TwoWheelerBrands")
                        .WithMany("TwoWheelers")
                        .HasForeignKey("TwoWBrandId")
                        .IsRequired();

                    b.Navigation("TwoWheelerBrands");
                });

            modelBuilder.Entity("Cars_Bikes.Models.UpcomingBike", b =>
                {
                    b.HasOne("Cars_Bikes.Models.TwoWheelerBrand", "TwoWheelerBrands")
                        .WithMany()
                        .HasForeignKey("TwoWBrandId");

                    b.Navigation("TwoWheelerBrands");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TwoWheeler", b =>
                {
                    b.Navigation("TWVarients");
                });

            modelBuilder.Entity("Cars_Bikes.Models.TwoWheelerBrand", b =>
                {
                    b.Navigation("TwoWheelers");
                });
#pragma warning restore 612, 618
        }
    }
}
